---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nigin-dep
  labels:
    author: jobair
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx
      author: jobair
  template:
    metadata:
      labels:
        name: nginx
        author: jobair
    spec:
      containers:
        - name: nginx-con
          image: nginx
...
