---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-de
  labels:
    app: mysqql
    author: jobair
spec:
  replicas: 3
  selector:
    matchLabels:
      type: webserver
      author: jobair
  template:
    metadata:
      name: mysql-pod
      labels:
        type: webserver
        author: jobair
    spec:
      containers:
        - name: mysql-con
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-se
                  key: pop
...
