---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dep
  labels:
    app: httpd
    creater: jobair
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
      creater: jobair
  template:
    metadata:
      name: job
      labels:
        app: httpd
        creater: jobair
    spec:
      containers:
        - name: httpd-con
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 9090
          resources:
            requests:
              cpu: "200m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
...
