---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dep
  labels:
    author: jobair
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
      author: jobair
  template:
    metadata:
      name: httpd-pod
      labels:
        app: httpd
        author: jobair
    spec:
      containers:
        - name: httpd-con
          image: httpd
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: slave1
                    operator: In
                    values:
                      - jobair1
...

