---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    author: jobair
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      name: httpd-pod
      labels:
        app: server
    spec: 
      containers:
        - name: httpd-con
          image: httpd
...
