---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    creator: jobair
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 7070
  selector:
    app: server
...
