---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    creator: jobair
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    app: webserver
...
